#!/bin/bash

help_doc="initialize working directory"

usage() {
    lkp_show "Usage: $PNAME $1 [OPTION]"
    lkp_print "\ninitialize working directory\n"
    lkp_print "\nOptions:\n"
    lkp_print "\t-d enable debug mode\n"
    lkp_print "\t-h list help\n"
    lkp_print "\nTo get more help, Please see the README.md\n"
}

source $ROOT_DIR/lib/env.sh
source $ROOT_DIR/lib/log.sh
source $ROOT_DIR/lib/init.sh
source $ROOT_DIR/lib/lkp.sh

# parse parameters
while getopts ":hd" opt; do
    case $opt in
    d) set -x;;
    h) usage $PROGRAM && exit 1;;
    ?) usage $PROGRAM && exit 1;;
    esac
done

mkdir -p $ROOT_DIR/log
mkdir -p $ROOT_DIR/results/local
mkdir -p $ROOT_DIR/results/remote
mkdir -p $ROOT_DIR/testcases
fs_init
lkp_install
