#!/bin/bash

help_doc="push the testcase to the nodes"

usage() {
    lkp_show "Usage: $PNAME $1 [OPTION]"
    lkp_print "\npush the testcase to the nodes\n"
    lkp_print "\nOptions:\n"
    lkp_print "\t-d enable debug mode\n"
    lkp_print "\t-h list help\n"
    lkp_print "\nTo get more help, Please see the README.md\n"
}

source $ROOT_DIR/lib/env.sh
source $ROOT_DIR/lib/log.sh

# parse parameters
while getopts ":hd" opt; do
    case $opt in
    d) set -x;;
    h) usage $PROGRAM && exit 1;;
    ?) usage $PROGRAM && exit 1;;
    esac
done


testcase="$@"  # testcase group

if [ ! -f $ROOT_DIR/testcases/$testcase ]; then
lkp_show "Error: push testcase does not exist!"
exit 0
fi

$SRC_PATH/build/lkp_extent_CLI PUSH $testcase $NODE_ID 0 $ROOT_DIR




