#!/bin/bash

help_doc="start lkp service"

usage() {
    lkp_show "Usage: $PNAME $1 [OPTION]"
    lkp_print "\nstart lkp server\n"
    lkp_print "\nOptions:\n"
    lkp_print "\t-d enable debug mode\n"
    lkp_print "\t-h list help\n"
    lkp_print "\nTo get more help, Please see the README.md\n"
}

source $ROOT_DIR/lib/env.sh
source $ROOT_DIR/lib/log.sh

# parse parameters
while getopts ":hd" opt; do
    case $opt in
    d) set -x;;
    h) usage $PROGRAM && exit 1;;
    ?) usage $PROGRAM && exit 1;;
    esac
done

set -e
for pid in $(ps -ef | grep -E "lkp-extent/src/build|lkp-tests" | awk '$8 !~ /grep/,/stop/ {print $2}');do
    kill $pid
done

lkp_show "lkp-exent service stop!"
