// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: sched.proto

package sched

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskMetaData_RoleType int32

const (
	TaskMetaData_RESERVE   TaskMetaData_RoleType = 0
	TaskMetaData_HOST      TaskMetaData_RoleType = 1
	TaskMetaData_CONTAINER TaskMetaData_RoleType = 2
)

// Enum value maps for TaskMetaData_RoleType.
var (
	TaskMetaData_RoleType_name = map[int32]string{
		0: "RESERVE",
		1: "HOST",
		2: "CONTAINER",
	}
	TaskMetaData_RoleType_value = map[string]int32{
		"RESERVE":   0,
		"HOST":      1,
		"CONTAINER": 2,
	}
)

func (x TaskMetaData_RoleType) Enum() *TaskMetaData_RoleType {
	p := new(TaskMetaData_RoleType)
	*p = x
	return p
}

func (x TaskMetaData_RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskMetaData_RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_sched_proto_enumTypes[0].Descriptor()
}

func (TaskMetaData_RoleType) Type() protoreflect.EnumType {
	return &file_sched_proto_enumTypes[0]
}

func (x TaskMetaData_RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskMetaData_RoleType.Descriptor instead.
func (TaskMetaData_RoleType) EnumDescriptor() ([]byte, []int) {
	return file_sched_proto_rawDescGZIP(), []int{0, 0}
}

type TaskMetaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string                `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Role TaskMetaData_RoleType `protobuf:"varint,2,opt,name=Role,proto3,enum=sched.TaskMetaData_RoleType" json:"Role,omitempty"`
}

func (x *TaskMetaData) Reset() {
	*x = TaskMetaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sched_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TaskMetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskMetaData) ProtoMessage() {}

func (x *TaskMetaData) ProtoReflect() protoreflect.Message {
	mi := &file_sched_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskMetaData.ProtoReflect.Descriptor instead.
func (*TaskMetaData) Descriptor() ([]byte, []int) {
	return file_sched_proto_rawDescGZIP(), []int{0}
}

func (x *TaskMetaData) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *TaskMetaData) GetRole() TaskMetaData_RoleType {
	if x != nil {
		return x.Role
	}
	return TaskMetaData_RESERVE
}

// -------------------------------------------------
// |                API Definition                 |
// -------------------------------------------------
type CasePushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID   string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	File []byte `protobuf:"bytes,3,opt,name=File,proto3" json:"File,omitempty"`
}

func (x *CasePushRequest) Reset() {
	*x = CasePushRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sched_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CasePushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasePushRequest) ProtoMessage() {}

func (x *CasePushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sched_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasePushRequest.ProtoReflect.Descriptor instead.
func (*CasePushRequest) Descriptor() ([]byte, []int) {
	return file_sched_proto_rawDescGZIP(), []int{1}
}

func (x *CasePushRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CasePushRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CasePushRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type CasePushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CasePushResponse) Reset() {
	*x = CasePushResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sched_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CasePushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CasePushResponse) ProtoMessage() {}

func (x *CasePushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sched_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CasePushResponse.ProtoReflect.Descriptor instead.
func (*CasePushResponse) Descriptor() ([]byte, []int) {
	return file_sched_proto_rawDescGZIP(), []int{2}
}

type JobRunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CaseID   string          `protobuf:"bytes,1,opt,name=CaseID,proto3" json:"CaseID,omitempty"`
	CaseName string          `protobuf:"bytes,2,opt,name=CaseName,proto3" json:"CaseName,omitempty"`
	Tasks    []*TaskMetaData `protobuf:"bytes,3,rep,name=Tasks,proto3" json:"Tasks,omitempty"`
}

func (x *JobRunRequest) Reset() {
	*x = JobRunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sched_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRunRequest) ProtoMessage() {}

func (x *JobRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sched_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRunRequest.ProtoReflect.Descriptor instead.
func (*JobRunRequest) Descriptor() ([]byte, []int) {
	return file_sched_proto_rawDescGZIP(), []int{3}
}

func (x *JobRunRequest) GetCaseID() string {
	if x != nil {
		return x.CaseID
	}
	return ""
}

func (x *JobRunRequest) GetCaseName() string {
	if x != nil {
		return x.CaseName
	}
	return ""
}

func (x *JobRunRequest) GetTasks() []*TaskMetaData {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type JobRunResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *JobRunResponse) Reset() {
	*x = JobRunResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sched_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JobRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRunResponse) ProtoMessage() {}

func (x *JobRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sched_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRunResponse.ProtoReflect.Descriptor instead.
func (*JobRunResponse) Descriptor() ([]byte, []int) {
	return file_sched_proto_rawDescGZIP(), []int{4}
}

var File_sched_proto protoreflect.FileDescriptor

var file_sched_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x22, 0x82, 0x01, 0x0a, 0x0c, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x74,
	0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x30, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x22, 0x30, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45, 0x10, 0x00,
	0x12, 0x08, 0x0a, 0x04, 0x48, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x4f,
	0x4e, 0x54, 0x41, 0x49, 0x4e, 0x45, 0x52, 0x10, 0x02, 0x22, 0x49, 0x0a, 0x0f, 0x43, 0x61, 0x73,
	0x65, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x46, 0x69, 0x6c, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x43, 0x61, 0x73, 0x65, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6e, 0x0a, 0x0d, 0x4a, 0x6f, 0x62, 0x52,
	0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x61, 0x73,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x43, 0x61, 0x73, 0x65, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x61, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a,
	0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x2e, 0x54, 0x61, 0x73, 0x6b, 0x4d, 0x65, 0x74, 0x61, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x05, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x10, 0x0a, 0x0e, 0x4a, 0x6f, 0x62, 0x52,
	0x75, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x7b, 0x0a, 0x05, 0x53, 0x63,
	0x68, 0x65, 0x64, 0x12, 0x3b, 0x0a, 0x08, 0x43, 0x61, 0x73, 0x65, 0x50, 0x75, 0x73, 0x68, 0x12,
	0x16, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x50, 0x75, 0x73, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x2e,
	0x43, 0x61, 0x73, 0x65, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x35, 0x0a, 0x06, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x12, 0x14, 0x2e, 0x73, 0x63, 0x68,
	0x65, 0x64, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x75, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x73, 0x63, 0x68,
	0x65, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sched_proto_rawDescOnce sync.Once
	file_sched_proto_rawDescData = file_sched_proto_rawDesc
)

func file_sched_proto_rawDescGZIP() []byte {
	file_sched_proto_rawDescOnce.Do(func() {
		file_sched_proto_rawDescData = protoimpl.X.CompressGZIP(file_sched_proto_rawDescData)
	})
	return file_sched_proto_rawDescData
}

var file_sched_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sched_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_sched_proto_goTypes = []interface{}{
	(TaskMetaData_RoleType)(0), // 0: sched.TaskMetaData.RoleType
	(*TaskMetaData)(nil),       // 1: sched.TaskMetaData
	(*CasePushRequest)(nil),    // 2: sched.CasePushRequest
	(*CasePushResponse)(nil),   // 3: sched.CasePushResponse
	(*JobRunRequest)(nil),      // 4: sched.JobRunRequest
	(*JobRunResponse)(nil),     // 5: sched.JobRunResponse
}
var file_sched_proto_depIdxs = []int32{
	0, // 0: sched.TaskMetaData.Role:type_name -> sched.TaskMetaData.RoleType
	1, // 1: sched.JobRunRequest.Tasks:type_name -> sched.TaskMetaData
	2, // 2: sched.Sched.CasePush:input_type -> sched.CasePushRequest
	4, // 3: sched.Sched.JobRun:input_type -> sched.JobRunRequest
	3, // 4: sched.Sched.CasePush:output_type -> sched.CasePushResponse
	5, // 5: sched.Sched.JobRun:output_type -> sched.JobRunResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_sched_proto_init() }
func file_sched_proto_init() {
	if File_sched_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sched_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TaskMetaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sched_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CasePushRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sched_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CasePushResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sched_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobRunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sched_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JobRunResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sched_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sched_proto_goTypes,
		DependencyIndexes: file_sched_proto_depIdxs,
		EnumInfos:         file_sched_proto_enumTypes,
		MessageInfos:      file_sched_proto_msgTypes,
	}.Build()
	File_sched_proto = out.File
	file_sched_proto_rawDesc = nil
	file_sched_proto_goTypes = nil
	file_sched_proto_depIdxs = nil
}
